### ISSUE TITLE
Site isn't very mobile friendly

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [cmderdev/cmderdev.github.io#15]
I mentioned cmder to a friend recently. Their reaction was to look it up on their phone. This was the experience they got:

![image](https://cloud.githubusercontent.com/assets/3335181/23863952/545cc17e-07ce-11e7-86b3-1129be261f26.png)
![image](https://cloud.githubusercontent.com/assets/3335181/23863981/6e5c8dca-07ce-11e7-966c-8aa42348be96.png)

😦

**Comment by JoshuaKGoldberg** [comment]
Some thoughts on ways to improve this:

* Use HTML elements + CSS to create the window in [main.jpg](http://cmder.net/img/main.jpg)
    * ...then use JavaScript to animate someone typing in random commands, maybe? That effect always looks cool...
* After ^, hide the background image on mobile
* Use flexbox for the three column layout, turning it into three rows on thin windows

**Comment by samvasko** [comment]
Would you be interested on working on making the site more responsive @JoshuaKGoldberg ?

**Comment by JoshuaKGoldberg** [comment]
I would, if you're willing to wait a little while. I'm taken through the end of the summer...

**Comment by schaazzz** [comment]
@JoshuaKGoldberg @samvasko 
I'd be willing to put in some to time help make the site more responsive :)

- Why not make life easy and just switch to Bootstrap? Easy to integrate and is responsive out of the box!

- A terminal session GIF (recorded using, for example, [Screen2GIF](https://github.com/NickeManarin/ScreenToGif)) can also be used to show commands being typed. 
    - ...alternatively, a static image can be shown initially, which can be replaced after a few seconds with the GIF using JS.

**Comment by samvasko** [comment]
@schaazzz It currently has a grid system and I think it just needs bit of tweaking for different viewports. And give a the gif a try! I am happy to add to to main project README as well. 👍

**Comment by DRSDavidSoft** [comment]
@JoshuaKGoldberg I wrote a fix in #22 by replacing lemonade to the new bootstrap, which uses flexboxes.

I've also been working on a HTML+CSS recreation of the window, instead of the current jpeg file.

I currently have a working demo that you can have a look at in my `rewrite` branch here: 
https://github.com/DRSDavidSoft/cmderdev.github.io/blob/gh-pages/.workspace/cmder-web.html

**The discussion has been moved here: [cmder-site/rewrite#15](https://github.com/DRSDavidSoft/cmder-site/issues/15)**

I think this approach is better than simply embedding a gif file, as it won't look good on >100% dpi displays, takes a lot of useless disk-space space and bandwidth, and _most importantly_ is not responsive. Instead, I've used [jQuery Terminal](https://github.com/jcubic/jquery.terminal) to actually display a terminal with text.

I hope @samvasko approves! he doesn't seem to work on Cmder these days. I wonder if he's still on Windows, or switched to Linux/macOS.

Anyways, as @schaazzz suggests, we can use an image polyfill at first, and after the terminal window is created, replace it with that. But it won't be needed as these days everybody seems to have Javascript enabled. It's enabled by default on Android/iOS, Chrome & Edge on Windows.



I'd like to work on the website and make it look better and more intuitive for the user in summer, as well.

So, if @JoshuaKGoldberg and @schaazzz have time to work on the website (and they're still interested to), please collaborate on the `rewrite` branch instead of creating a new fork.

**Comment by DRSDavidSoft** [comment]
@Stanzilla 

<img width="505" alt="cmder-hyper-git" src="https://user-images.githubusercontent.com/4673812/39090813-d3969604-45fd-11e8-8908-25bae0aba69a.png">

I'm also working to make sure Cmder runs as well in Hyper and VS Code as it's running in ConEmu, so I'll document them on the website. With the Zeit team incorporating `xterm.js` into Hyper, it'd work as great as VS Code.

How does it look?

**Comment by Stanzilla** [comment]
What would making sure of that entail exactly?

**Comment by DRSDavidSoft** [comment]
@Stanzilla I've explained it here: https://github.com/DRSDavidSoft/cmderdev.github.io/issues/12
